package forex.trainer.ac.za.model.account;

public enum Permission
{
    CUSTOMER_DELETE,
    CUSTOMER_READ,
    CUSTOMER_WRITE,
    CUSTOMER_UPDATE,
    ADMINISTRATOR_READ,
    ADMINISTRATOR_WRITE,
    ADMINISTRATOR_DELETE,
    ADMINISTRATOR_UPDATE,
    SUPER_ADMINISTRATOR_READ,
    SUPER_ADMINISTRATOR_WRITE,
    SUPER_ADMINISTRATOR_DELETE,
    SUPER_ADMINISTRATOR_UPDATE,
}
